name: console_plus
description: A Flutter plugin that provides an elegant in-app developer console with
  floating button.
version: 1.1.1
documentation: https://github.com/ashish8381/console_plus#readme
homepage: https://github.com/ashish8381/console_plus
repository: https://github.com/ashish8381/console_plus

screenshots:
  - description: "Console+ Plugin Logo"
    path: logo.png
  - description: "Floating Console UI with Log Filters"
    path: example/screenshots/console.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js_interop: ^0.0.1
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1
  path_provider: ^2.1.5
  file_saver: ^0.3.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ashish.console_plus
        pluginClass: ConsolePlusPlugin
      ios:
        pluginClass: ConsolePlusPlugin
        iosPrefix: CP
      web:
        pluginClass: ConsolePlusWeb
        fileName: console_plus_web.dart
