name: console_plus
description: A Flutter plugin for in-app debug console with floating button, log filtering, export, auto-scroll etc.
version: 0.0.2
documentation: https://github.com/ashish8381/console_plus#readme
homepage: https://github.com/ashish8381/console_plus # Optional
repository: https://github.com/ashish8381/console_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js_interop: ^0.0.1
  plugin_platform_interface: ^2.1.5
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ashish.console_plus
        pluginClass: ConsolePlusPlugin
      ios:
        pluginClass: ConsolePlusPlugin
        iosPrefix: CP
      web:
        pluginClass: ConsolePlusWeb
        fileName: console_plus_web.dart
